/*
 * Copyright © 2024 Vitaliy Triang3l Kuzmin
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#include "terascale_format.h"

#include <assert.h>
#include <stddef.h>

const uint8_t terascale_format_block_texels_log2[1 << 6][2] = {
   [TERASCALE_FORMAT_INDEX_1] = {3, 0},     [TERASCALE_FORMAT_INDEX_1_REVERSED] = {3, 0},
   [TERASCALE_FORMAT_INDEX_GB_GR] = {1, 0}, [TERASCALE_FORMAT_INDEX_BG_RG] = {1, 0},
   [TERASCALE_FORMAT_INDEX_BC1] = {2, 2},   [TERASCALE_FORMAT_INDEX_BC2] = {2, 2},
   [TERASCALE_FORMAT_INDEX_BC3] = {2, 2},   [TERASCALE_FORMAT_INDEX_BC4] = {2, 2},
   [TERASCALE_FORMAT_INDEX_BC5] = {2, 2},   [TERASCALE_FORMAT_INDEX_BC6] = {2, 2},
   [TERASCALE_FORMAT_INDEX_BC7] = {2, 2},   [TERASCALE_FORMAT_INDEX_CTX1] = {2, 2},
};

const uint8_t terascale_format_bytes_per_block[1 << 6] = {
   [TERASCALE_FORMAT_INDEX_8] = 1,
   [TERASCALE_FORMAT_INDEX_4_4] = 1,
   [TERASCALE_FORMAT_INDEX_3_3_2] = 1,
   [TERASCALE_FORMAT_INDEX_16] = 2,
   [TERASCALE_FORMAT_INDEX_16_FLOAT] = 2,
   [TERASCALE_FORMAT_INDEX_8_8] = 2,
   [TERASCALE_FORMAT_INDEX_5_6_5] = 2,
   [TERASCALE_FORMAT_INDEX_6_5_5] = 2,
   [TERASCALE_FORMAT_INDEX_1_5_5_5] = 2,
   [TERASCALE_FORMAT_INDEX_4_4_4_4] = 2,
   [TERASCALE_FORMAT_INDEX_5_5_5_1] = 2,
   [TERASCALE_FORMAT_INDEX_32] = 4,
   [TERASCALE_FORMAT_INDEX_32_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_16_16] = 4,
   [TERASCALE_FORMAT_INDEX_16_16_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_8_24] = 4,
   [TERASCALE_FORMAT_INDEX_8_24_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_24_8] = 4,
   [TERASCALE_FORMAT_INDEX_24_8_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_10_11_11] = 4,
   [TERASCALE_FORMAT_INDEX_10_11_11_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_11_11_10] = 4,
   [TERASCALE_FORMAT_INDEX_11_11_10_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_2_10_10_10] = 4,
   [TERASCALE_FORMAT_INDEX_8_8_8_8] = 4,
   [TERASCALE_FORMAT_INDEX_10_10_10_2] = 4,
   [TERASCALE_FORMAT_INDEX_X24_8_32_FLOAT] = 8,
   [TERASCALE_FORMAT_INDEX_32_32] = 8,
   [TERASCALE_FORMAT_INDEX_32_32_FLOAT] = 8,
   [TERASCALE_FORMAT_INDEX_16_16_16_16] = 8,
   [TERASCALE_FORMAT_INDEX_16_16_16_16_FLOAT] = 8,
   [TERASCALE_FORMAT_INDEX_32_32_32_32] = 16,
   [TERASCALE_FORMAT_INDEX_32_32_32_32_FLOAT] = 16,
   [TERASCALE_FORMAT_INDEX_1] = 1,
   [TERASCALE_FORMAT_INDEX_1_REVERSED] = 1,
   [TERASCALE_FORMAT_INDEX_GB_GR] = 4,
   [TERASCALE_FORMAT_INDEX_BG_RG] = 4,
   [TERASCALE_FORMAT_INDEX_32_AS_8] = 4,
   [TERASCALE_FORMAT_INDEX_32_AS_8_8] = 4,
   [TERASCALE_FORMAT_INDEX_5_9_9_9_SHAREDEXP] = 4,
   [TERASCALE_FORMAT_INDEX_8_8_8] = 3,
   [TERASCALE_FORMAT_INDEX_16_16_16] = 6,
   [TERASCALE_FORMAT_INDEX_16_16_16_FLOAT] = 6,
   [TERASCALE_FORMAT_INDEX_32_32_32] = 12,
   [TERASCALE_FORMAT_INDEX_32_32_32_FLOAT] = 12,
   [TERASCALE_FORMAT_INDEX_BC1] = 8,
   [TERASCALE_FORMAT_INDEX_BC2] = 16,
   [TERASCALE_FORMAT_INDEX_BC3] = 16,
   [TERASCALE_FORMAT_INDEX_BC4] = 8,
   [TERASCALE_FORMAT_INDEX_BC5] = 16,
   [TERASCALE_FORMAT_INDEX_BC6] = 16,
   [TERASCALE_FORMAT_INDEX_BC7] = 16,
   [TERASCALE_FORMAT_INDEX_32_AS_32_32_32_32] = 4,
   [TERASCALE_FORMAT_INDEX_CTX1] = 8,
};

const uint8_t terascale_format_big_endian_swap[1 << 6] = {
   [TERASCALE_FORMAT_INDEX_16] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_16_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_5_6_5] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_6_5_5] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_1_5_5_5] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_4_4_4_4] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_5_5_5_1] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_32] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_16_16] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_16_16_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_8_24] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_8_24_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_24_8] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_24_8_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_10_11_11] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_10_11_11_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_11_11_10] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_11_11_10_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_2_10_10_10] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_10_10_10_2] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_X24_8_32_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_32] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_32_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_16_16_16_16] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_16_16_16_16_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_32_32_32_32] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_32_32_32_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_AS_8] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_AS_8_8] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_5_9_9_9_SHAREDEXP] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_16_16_16] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_16_16_16_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN16,
   [TERASCALE_FORMAT_INDEX_32_32_32] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_32_32_FLOAT] = TERASCALE_ENDIAN_SWAP_8IN32,
   [TERASCALE_FORMAT_INDEX_32_AS_32_32_32_32] = TERASCALE_ENDIAN_SWAP_8IN32,
};

const uint8_t terascale_format_channel_count[1 << 6] = {
   [TERASCALE_FORMAT_INDEX_8] = 1,
   [TERASCALE_FORMAT_INDEX_4_4] = 2,
   [TERASCALE_FORMAT_INDEX_3_3_2] = 3,
   [TERASCALE_FORMAT_INDEX_16] = 1,
   [TERASCALE_FORMAT_INDEX_16_FLOAT] = 1,
   [TERASCALE_FORMAT_INDEX_8_8] = 2,
   [TERASCALE_FORMAT_INDEX_5_6_5] = 3,
   [TERASCALE_FORMAT_INDEX_6_5_5] = 3,
   [TERASCALE_FORMAT_INDEX_1_5_5_5] = 4,
   [TERASCALE_FORMAT_INDEX_4_4_4_4] = 4,
   [TERASCALE_FORMAT_INDEX_5_5_5_1] = 4,
   [TERASCALE_FORMAT_INDEX_32] = 1,
   [TERASCALE_FORMAT_INDEX_32_FLOAT] = 1,
   [TERASCALE_FORMAT_INDEX_16_16] = 2,
   [TERASCALE_FORMAT_INDEX_16_16_FLOAT] = 2,
   [TERASCALE_FORMAT_INDEX_8_24] = 2,
   [TERASCALE_FORMAT_INDEX_8_24_FLOAT] = 2,
   [TERASCALE_FORMAT_INDEX_24_8] = 2,
   [TERASCALE_FORMAT_INDEX_24_8_FLOAT] = 2,
   [TERASCALE_FORMAT_INDEX_10_11_11] = 3,
   [TERASCALE_FORMAT_INDEX_10_11_11_FLOAT] = 3,
   [TERASCALE_FORMAT_INDEX_11_11_10] = 3,
   [TERASCALE_FORMAT_INDEX_11_11_10_FLOAT] = 3,
   [TERASCALE_FORMAT_INDEX_2_10_10_10] = 4,
   [TERASCALE_FORMAT_INDEX_8_8_8_8] = 4,
   [TERASCALE_FORMAT_INDEX_10_10_10_2] = 4,
   /* Different from the number of channels (3) in the respective pipe_formats. */
   [TERASCALE_FORMAT_INDEX_X24_8_32_FLOAT] = 2,
   [TERASCALE_FORMAT_INDEX_32_32] = 2,
   [TERASCALE_FORMAT_INDEX_32_32_FLOAT] = 2,
   [TERASCALE_FORMAT_INDEX_16_16_16_16] = 4,
   [TERASCALE_FORMAT_INDEX_16_16_16_16_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_32_32_32_32] = 4,
   [TERASCALE_FORMAT_INDEX_32_32_32_32_FLOAT] = 4,
   [TERASCALE_FORMAT_INDEX_1] = 1,
   [TERASCALE_FORMAT_INDEX_1_REVERSED] = 1,
   [TERASCALE_FORMAT_INDEX_GB_GR] = 3,
   [TERASCALE_FORMAT_INDEX_BG_RG] = 3,
   [TERASCALE_FORMAT_INDEX_5_9_9_9_SHAREDEXP] = 3,
   [TERASCALE_FORMAT_INDEX_8_8_8] = 3,
   [TERASCALE_FORMAT_INDEX_16_16_16] = 3,
   [TERASCALE_FORMAT_INDEX_16_16_16_FLOAT] = 3,
   [TERASCALE_FORMAT_INDEX_32_32_32] = 3,
   [TERASCALE_FORMAT_INDEX_32_32_32_FLOAT] = 3,
   [TERASCALE_FORMAT_INDEX_BC1] = 4,
   [TERASCALE_FORMAT_INDEX_BC2] = 4,
   [TERASCALE_FORMAT_INDEX_BC3] = 4,
   [TERASCALE_FORMAT_INDEX_BC4] = 1,
   [TERASCALE_FORMAT_INDEX_BC5] = 2,
   [TERASCALE_FORMAT_INDEX_BC6] = 3,
   [TERASCALE_FORMAT_INDEX_BC7] = 4,
   [TERASCALE_FORMAT_INDEX_CTX1] = 2,
};

const uint8_t terascale_format_cb_color_export_component_masks[4 + 1][4] = {
   [0] = {},
   [1] =
      {
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD] = 0b0001,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT] = 0b0010,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD_REV] = 0b0100,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT_REV] = 0b1000,
      },
   [2] =
      {
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD] = 0b0011,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT] = 0b1001,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD_REV] = 0b0011,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT_REV] = 0b1001,
      },
   [3] =
      {
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD] = 0b0111,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT] = 0b1011,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD_REV] = 0b0111,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT_REV] = 0b1011,
      },
   [4] =
      {
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD] = 0b1111,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT] = 0b1111,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_STD_REV] = 0b1111,
         [TERASCALE_FORMAT_CB_COLOR_SWAP_ALT_REV] = 0b1111,
      },
};

enum terascale_r6xx_depth_stencil_format
terascale_get_r6xx_depth_stencil_format(const enum pipe_format format)
{
   switch (format) {
   case PIPE_FORMAT_Z16_UNORM:
      return TERASCALE_R6XX_DEPTH_STENCIL_FORMAT_16;
   case PIPE_FORMAT_Z32_FLOAT:
      return TERASCALE_R6XX_DEPTH_STENCIL_FORMAT_32_FLOAT;
   case PIPE_FORMAT_Z24_UNORM_S8_UINT:
   case PIPE_FORMAT_X24S8_UINT:
      return TERASCALE_R6XX_DEPTH_STENCIL_FORMAT_8_24;
   case PIPE_FORMAT_Z24X8_UNORM:
      return TERASCALE_R6XX_DEPTH_STENCIL_FORMAT_X8_24;
   case PIPE_FORMAT_Z32_FLOAT_S8X24_UINT:
   case PIPE_FORMAT_X32_S8X24_UINT:
      /* Handled explicitly rather than via util_format_description channels to avoid the endianness
       * difference there (DB only works with little-endian data).
       */
      return TERASCALE_R6XX_DEPTH_STENCIL_FORMAT_X24_8_32_FLOAT;
   default:
      return TERASCALE_R6XX_DEPTH_STENCIL_FORMAT_INVALID;
   }
}

bool
terascale_get_r8xx_depth_stencil_format(const enum pipe_format format,
                                        enum terascale_r8xx_depth_format *const depth_format_out_opt,
                                        bool *const has_stencil_out_opt)
{
   enum terascale_r8xx_depth_format depth_format = TERASCALE_R8XX_DEPTH_FORMAT_INVALID;
   bool has_stencil = false;

   switch (format) {
   case PIPE_FORMAT_S8_UINT:
   case PIPE_FORMAT_X24S8_UINT:
   case PIPE_FORMAT_S8X24_UINT:
   case PIPE_FORMAT_X32_S8X24_UINT:
      has_stencil = true;
      break;
   case PIPE_FORMAT_Z16_UNORM:
      depth_format = TERASCALE_R8XX_DEPTH_FORMAT_16;
      break;
   case PIPE_FORMAT_Z16_UNORM_S8_UINT:
      depth_format = TERASCALE_R8XX_DEPTH_FORMAT_16;
      has_stencil = true;
      break;
   case PIPE_FORMAT_Z32_FLOAT:
      depth_format = TERASCALE_R8XX_DEPTH_FORMAT_32_FLOAT;
      break;
   case PIPE_FORMAT_Z24_UNORM_S8_UINT:
      depth_format = TERASCALE_R8XX_DEPTH_FORMAT_24;
      has_stencil = true;
      break;
   /* PIPE_FORMAT_S8_UINT_Z24_UNORM and PIPE_FORMAT_X8Z24_UNORM are not supported because their
    * corresponding color formats assume that the depth is in bits [31:8] of each dword rather than
    * [23:0].
    */
   case PIPE_FORMAT_Z24X8_UNORM:
      depth_format = TERASCALE_R8XX_DEPTH_FORMAT_24;
      break;
   case PIPE_FORMAT_Z32_FLOAT_S8X24_UINT:
      depth_format = TERASCALE_R8XX_DEPTH_FORMAT_32_FLOAT;
      has_stencil = true;
      break;
   default:
      return false;
   }

   assert(depth_format != TERASCALE_R8XX_DEPTH_FORMAT_INVALID || has_stencil);
   if (depth_format_out_opt != NULL) {
      *depth_format_out_opt = depth_format;
   }
   if (has_stencil_out_opt != NULL) {
      *has_stencil_out_opt = has_stencil;
   }
   return true;
}
