#!/bin/bash -e

echo "// Autogenerated by aosp-gen-bp.sh" >Android.gen.bp
echo 'cc_defaults { name: "mesa_version_defaults", cflags: ["-DPACKAGE_VERSION=\"'$(cat VERSION)'\""] }' >>Android.gen.bp
bpfmt -w Android.gen.bp