/*
 * Copyright © 2024 Vitaliy Triang3l Kuzmin
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#ifndef TERAKAN_BARRIER_H
#define TERAKAN_BARRIER_H

#include "util/macros.h"

#ifdef __cplusplus
extern "C" {
#endif

enum terakan_barrier_action_flags {
   TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_CB_RTV_DATA,
   TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_CB_RTV_META,
   TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_CB_UAV,
   TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_DB_DATA,
   TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_DB_META,
   TERAKAN_BARRIER_ACTION_INDEX_PARTIAL_FLUSH_CP_THROUGH_PS,
   TERAKAN_BARRIER_ACTION_INDEX_PARTIAL_FLUSH_CP_THROUGH_VS,
   TERAKAN_BARRIER_ACTION_INDEX_PARTIAL_FLUSH_CS,
   TERAKAN_BARRIER_ACTION_INDEX_SYNC_ME_TO_CP_DMA,
   TERAKAN_BARRIER_ACTION_INDEX_SYNC_PFP_TO_ME,
   TERAKAN_BARRIER_ACTION_INDEX_INV_TC,
   TERAKAN_BARRIER_ACTION_INDEX_INV_VC,
   TERAKAN_BARRIER_ACTION_INDEX_INV_SH,

   /* Sufficient for CB MSAA resolves without flushing meta. */
   TERAKAN_BARRIER_ACTION_FLUSH_INV_CB_RTV_DATA =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_CB_RTV_DATA),
   TERAKAN_BARRIER_ACTION_FLUSH_INV_CB_RTV_META =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_CB_RTV_META),
   TERAKAN_BARRIER_ACTION_FLUSH_INV_CB_UAV =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_CB_UAV),
   TERAKAN_BARRIER_ACTION_FLUSH_INV_DB_DATA =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_DB_DATA),
   TERAKAN_BARRIER_ACTION_FLUSH_INV_DB_META =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_FLUSH_INV_DB_META),
   TERAKAN_BARRIER_ACTION_PARTIAL_FLUSH_CP_THROUGH_PS =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_PARTIAL_FLUSH_CP_THROUGH_PS),
   TERAKAN_BARRIER_ACTION_PARTIAL_FLUSH_CP_THROUGH_VS =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_PARTIAL_FLUSH_CP_THROUGH_VS),
   TERAKAN_BARRIER_ACTION_PARTIAL_FLUSH_CS =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_PARTIAL_FLUSH_CS),
   TERAKAN_BARRIER_ACTION_SYNC_ME_TO_CP_DMA =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_SYNC_ME_TO_CP_DMA),
   TERAKAN_BARRIER_ACTION_SYNC_PFP_TO_ME =
      BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_SYNC_PFP_TO_ME),
   TERAKAN_BARRIER_ACTION_INV_TC = BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_INV_TC),
   TERAKAN_BARRIER_ACTION_INV_VC = BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_INV_VC),
   TERAKAN_BARRIER_ACTION_INV_SH = BITFIELD_BIT(TERAKAN_BARRIER_ACTION_INDEX_INV_SH),
};

struct terakan_gfx_command_writer;

void terakan_barrier_emit_pending_actions(struct terakan_gfx_command_writer * command_writer);

#ifdef __cplusplus
}
#endif

#endif /* TERAKAN_BARRIER_H */
